apiVersion: v1
kind: Pod
metadata:
  name: perfanalyzer
spec:
  containers:
  - name: perfanalyzer
    image: nvcr.io/nvidia/tritonserver:23.05-py3-sdk
    command: ["tail", "-f", "/dev/null"]
    resources:
      limits:
        cpu: 2
        memory: 8Gi
      requests:
        cpu: 1
        memory: 2Gi