apiVersion: v1
kind: Service
metadata:
  name: triton
spec:
  selector:
    app: triton
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
  type: ClusterIP